name: S3 Sync

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Sync to S3
        run: |
          aws s3 sync . s3://${{ env.S3_BUCKET }}/${{ env.S3_PATH }} \
            --exclude ".git/*" --exclude ".github/*" \
            --exclude "README.md" --exclude ".gitignore" \
            --exclude "data" --exclude "config" \
            --exclude "plugins" --exclude "scripts" \
            --exlude "docker-compose.yml" \
            --exclude "notebooks" --exclude ".env" \ 
            --exclude "logs" \
            --delete
        env:
          S3_BUCKET: spotify-prod-self
          S3_PATH: mwaa-prod